const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d'),message=document.getElementById('message');
const title=message.querySelector('h2'),text=message.querySelector('p'),startButton=document.getElementById('startButton'),restartButton=document.getElementById('restartButton');
const parcelCount=document.getElementById('parcelCount'),timerLabel=document.getElementById('timer'),scoreLabel=document.getElementById('score'),levelLabel=document.getElementById('level');
const W=canvas.width,H=canvas.height;
const levels=[
 {time:60,p:[[180,105],[450,300],[730,455]],b:[[65,200,190,30],[315,80,34,170],[560,165,205,30],[220,395,190,32],[520,350,35,140]],e:[[390,190],[680,430]],c:[[120,120],[275,315],[600,100],[815,470]],x:[735,300]},
 {time:70,p:[[125,430],[420,110],[780,260],[650,480]],b:[[80,100,220,32],[365,50,32,190],[500,320,240,32],[180,280,32,190],[800,90,32,160]],e:[[330,390],[590,160],[820,390]],c:[[100,70],[330,270],[470,470],[760,100],[845,300]],x:[450,275]},
 {time:85,p:[[120,110],[300,470],[570,110],[790,450],[700,280]],b:[[55,200,250,32],[345,55,32,190],[490,200,260,32],[250,350,32,170],[780,70,32,170],[520,420,220,32]],e:[[380,350],[620,100],[820,350],[150,330]],c:[[100,470],[320,100],[430,300],[760,150],[840,490],[470,500]],x:[400,280]}
];
const player={x:80,y:H-78,r:17,speed:3.7,boost:0,invincible:0},van={x:W-92,y:74,w:58,h:36},keys={};
let level=0,running=false,timeLeft=60,score=0,lastTime=0,animation,audio,parcels=[],blocks=[],enemies=[],coins=[],power;
function loadLevel(i){level=i;const d=levels[i];timeLeft=d.time;parcels=d.p.map(([x,y])=>({x,y,found:false}));blocks=d.b.map(([x,y,w,h])=>({x,y,w,h}));enemies=d.e.map(([x,y],n)=>({x,y,r:15,dx:n%2?-1.2:1.2,dy:n%2?1.1:-1.1}));coins=d.c.map(([x,y])=>({x,y,taken:false}));power={x:d.x[0],y:d.x[1],taken:false};player.x=80;player.y=H-78;player.boost=0;player.invincible=0;updateHud();draw();}
function resetGame(){score=0;loadLevel(0)}
function start(){ensureAudio();resetGame();running=true;message.classList.add('hidden');cancelAnimationFrame(animation);lastTime=performance.now();animation=requestAnimationFrame(loop)}
function loop(now){if(!running)return;const dt=Math.min((now-lastTime)/1000,.05);lastTime=now;timeLeft-=dt;update(dt);draw();updateHud();if(timeLeft<=0)finish(false,'Time ran out','The parcels are still waiting. Try a faster route.');else animation=requestAnimationFrame(loop)}
function update(dt){let dx=0,dy=0;if(keys.ArrowLeft||keys.a)dx--;if(keys.ArrowRight||keys.d)dx++;if(keys.ArrowUp||keys.w)dy--;if(keys.ArrowDown||keys.s)dy++;if(dx||dy){const n=Math.hypot(dx,dy),s=player.speed+(player.boost>0?2:0);move(dx/n*s,dy/n*s)}if(player.boost>0)player.boost-=dt;if(player.invincible>0)player.invincible-=dt;
 enemies.forEach(e=>{e.x+=e.dx;e.y+=e.dy;if(e.x<e.r||e.x>W-e.r)e.dx*=-1;if(e.y<e.r||e.y>H-e.r)e.dy*=-1;if(player.invincible<=0&&Math.hypot(player.x-e.x,player.y-e.y)<player.r+e.r){score=Math.max(0,score-50);player.x=80;player.y=H-78;player.invincible=2;beep(120,.15)}});
 parcels.forEach(p=>{if(!p.found&&Math.hypot(player.x-p.x,player.y-p.y)<28){p.found=true;score+=100;beep(620,.1)}});coins.forEach(c=>{if(!c.taken&&Math.hypot(player.x-c.x,player.y-c.y)<25){c.taken=true;score+=25;beep(820,.07)}});if(power&&!power.taken&&Math.hypot(player.x-power.x,player.y-power.y)<27){power.taken=true;player.boost=8;score+=50;beep(960,.15)}
 if(parcels.every(p=>p.found)&&player.x>van.x-45&&player.x<van.x+van.w+25&&player.y>van.y-35&&player.y<van.y+van.h+35){score+=Math.ceil(timeLeft)*10;if(level<levels.length-1){beep(740,.2);loadLevel(level+1)}else finish(true,'All deliveries complete!',`Final score: ${score}`)}}
function move(dx,dy){const nx=Math.max(player.r,Math.min(W-player.r,player.x+dx)),ny=Math.max(player.r,Math.min(H-player.r,player.y+dy));if(!blocks.some(b=>circleRect(nx,player.y,player.r,b)))player.x=nx;if(!blocks.some(b=>circleRect(player.x,ny,player.r,b)))player.y=ny}
function circleRect(cx,cy,r,b){const x=Math.max(b.x,Math.min(cx,b.x+b.w)),y=Math.max(b.y,Math.min(cy,b.y+b.h));return Math.hypot(cx-x,cy-y)<r}
function finish(success,t,tx){running=false;title.textContent=t;text.textContent=tx;startButton.textContent=success?'Play again':'Try again';message.classList.remove('hidden');if(success)beep(980,.3)}
function updateHud(){parcelCount.textContent=`${parcels.filter(p=>p.found).length} / ${parcels.length}`;timerLabel.textContent=Math.max(0,Math.ceil(timeLeft));scoreLabel.textContent=score;levelLabel.textContent=`${level+1} / ${levels.length}`}
function ensureAudio(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}
function beep(freq,duration){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
function draw(){ctx.fillStyle='#11161c';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#1d2730';for(let x=0;x<W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}blocks.forEach(b=>{ctx.fillStyle='#263039';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#34414b';ctx.fillRect(b.x,b.y,b.w,5)});
 ctx.fillStyle='#55a7ff';ctx.fillRect(van.x,van.y,van.w,van.h);ctx.fillStyle='#b9e0ff';ctx.fillRect(van.x+9,van.y+7,17,12);ctx.fillRect(van.x+31,van.y+7,17,12);ctx.fillStyle='#101820';ctx.beginPath();ctx.arc(van.x+14,van.y+van.h,7,0,Math.PI*2);ctx.arc(van.x+45,van.y+van.h,7,0,Math.PI*2);ctx.fill();
 parcels.forEach(p=>{if(p.found)return;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(-.12);ctx.fillStyle='#d8893e';ctx.fillRect(-14,-12,28,24);ctx.strokeStyle='#ffd27e';ctx.strokeRect(-14,-12,28,24);ctx.fillStyle='#f5c875';ctx.fillRect(-2,-12,4,24);ctx.restore()});coins.forEach(c=>{if(c.taken)return;ctx.fillStyle='#ffe06a';ctx.beginPath();ctx.arc(c.x,c.y,9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#9b6915';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillText('$',c.x,c.y+4)});if(power&&!power.taken){ctx.fillStyle='#8d7cff';ctx.beginPath();ctx.arc(power.x,power.y,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='white';ctx.font='bold 16px sans-serif';ctx.textAlign='center';ctx.fillText('⚡',power.x,power.y+6)};enemies.forEach(e=>{ctx.fillStyle='#ee5b69';ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#32131a';ctx.beginPath();ctx.arc(e.x-5,e.y-2,3,0,Math.PI*2);ctx.arc(e.x+5,e.y-2,3,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=player.invincible>0&&Math.floor(player.invincible*8)%2===0?.35:1;ctx.fillStyle='#ffb84d';ctx.beginPath();ctx.arc(player.x,player.y,player.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys[e.key]=true});window.addEventListener('keyup',e=>{keys[e.key]=false});document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;['pointerdown','touchstart'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();keys[k]=true}));['pointerup','pointerleave','pointercancel','touchend'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();keys[k]=false}))});startButton.addEventListener('click',start);restartButton.addEventListener('click',start);resetGame();
